ALTER TABLE claims
  ADD COLUMN IF NOT EXISTS identifying_marks JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS photos JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS pickup_method TEXT NOT NULL DEFAULT 'in_person',
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS availability TEXT;
